[package]
name = "g3-cache-macros"
version = "0.1.0"

edition = "2024"
description = "Proc macro support for g3-cache."
repository = "https://github.com/g3techhq/g3-cache"
readme = "README.md"
documentation = "https://docs.rs/g3-cache-macros"
license = "MIT OR Apache-2.0"
keywords = ["dioxus", "cache", "macro"]
categories = ["development-tools::procedural-macro-helpers", "caching"]
include = ["Cargo.toml", "README.md", "CHANGELOG.md", "LICENSE-MIT", "LICENSE-APACHE", "src/**"]

[lib]
name = "g3_cache_macros"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit"] }
